# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - detector: yolov5.yaml
  - model: regressor.yaml
  - augmentation: inference_preprocessing.yaml

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# root directory
root: ${hydra:runtime.cwd}

# calib_file
calib_file: ${root}/data/global_calib.txt

# save 2D bounding box
save_det2d: False

# regressor weights
regressor_weights: ${root}/weights/regressor_001.pt

# source directory
source_dir: ${root}/data/demo/images

# dump directory
dump_dir: ${root}/runs
